base:
	g++ -o cubeMapper png.cpp main*base*.cpp common.cpp realm*.cpp stamp*.cpp -lpng -O02
higher:
	g++ -o cubeMapper png.cpp main*higher*.cpp common.cpp realm*.cpp stamp*.cpp -lpng -O02
clean:
	rm cubeMapper
