default:
	g++ main.cpp dsgl.cpp dsglMeshes.cpp gl3w.c -o VoronoiNoise -lglfw -lGL -ldl -D DSGL_DEBUG -D DSGL_GLFW -D DSGL_GL3W -std=c++11 -O2
crack:
	g++ -D VORONOI_CRACK main.cpp dsgl.cpp dsglMeshes.cpp gl3w.c -o VoronoiNoise -lglfw -lGL -ldl -D DSGL_DEBUG -D DSGL_GLFW -D DSGL_GL3W -std=c++11 -O2
jelly:
	g++ -D VORONOI_JELLY main.cpp dsgl.cpp dsglMeshes.cpp gl3w.c -o VoronoiNoise -lglfw -lGL -ldl -D DSGL_DEBUG -D DSGL_GLFW -D DSGL_GL3W -std=c++11 -O2
